
import React, { useState } from 'react';
import { Clipboard, ChevronDown, ChevronUp, MessageSquare, AlertTriangle, FileText, Check } from 'lucide-react';
import { ComplaintData } from '../lib/complaintTypes';

interface ComplaintOutputProps {
  complaintData: Partial<ComplaintData>;
  onSave: () => void;
}

const ComplaintOutput: React.FC<ComplaintOutputProps> = ({ complaintData, onSave }) => {
  const [copied, setCopied] = useState(false);
  const [showSimplified, setShowSimplified] = useState(true);

  const handleCopy = () => {
    navigator.clipboard.writeText(sampleFormalComplaint);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const toggleSection = (section: 'simplified') => {
    if (section === 'simplified') {
      setShowSimplified(!showSimplified);
    }
  };

  // In a real application, this would be generated by the AI
  const sampleFormalComplaint = `À ${complaintData.company?.name},

Venho por meio desta formalizar reclamação referente a ${complaintType(complaintData)} ocorrido em ${formatDate(complaintData.occurrenceDate)}.

FATOS:
${complaintData.description}

${complaintData.contactAttempt ? `Informo que já tentei resolver a questão diretamente com a empresa através de ${complaintData.contactDescription}, sem sucesso.` : ''}

FUNDAMENTAÇÃO LEGAL:
De acordo com o Código de Defesa do Consumidor, especificamente em seu Art. 6º, são direitos básicos do consumidor a proteção contra métodos comerciais coercitivos ou desleais, bem como contra práticas e cláusulas abusivas ou impostas no fornecimento de produtos e serviços.

PEDIDO:
Diante do exposto, solicito:
1. A resolução do problema apresentado no prazo de 5 (cinco) dias úteis;
2. Compensação pelos transtornos causados;
3. Compromisso de melhorias para evitar situações semelhantes no futuro.

Caso não haja manifestação ou resolução satisfatória no prazo estipulado, tomarei as medidas cabíveis junto aos órgãos de defesa do consumidor e, se necessário, ao Poder Judiciário.

Atenciosamente,
[Seu nome]
[Seus dados de contato]`;

  // In a real application, this would be generated by the AI
  const simplifiedExplanation = `Com base nas informações fornecidas, você está protegido(a) pelo Código de Defesa do Consumidor.

No seu caso específico:
• ${complaintData.complaintType === 'atraso_entrega' ? 'O atraso na entrega sem justificativa viola o Art. 35 do CDC' : 
  complaintData.complaintType === 'cobranca_indevida' ? 'A cobrança por serviços não contratados viola o Art. 39 do CDC' : 
  complaintData.complaintType === 'produto_defeituoso' ? 'Produtos com defeito devem ser reparados em até 30 dias (Art. 18 do CDC)' : 
  'A situação viola direitos básicos do consumidor previstos no CDC'}

• Você tem direito a: ${complaintData.complaintType === 'atraso_entrega' ? 'exigir a entrega imediata do produto, aceitar outro produto equivalente ou cancelar a compra com devolução integral' : 
  complaintData.complaintType === 'cobranca_indevida' ? 'devolução em dobro do valor cobrado indevidamente' : 
  complaintData.complaintType === 'produto_defeituoso' ? 'troca do produto, devolução do dinheiro ou abatimento proporcional do preço' : 
  'reparação pelos danos materiais e morais causados'}

• Prazo para reclamar: ${complaintData.complaintType === 'produto_defeituoso' ? '30 dias para produtos não-duráveis e 90 dias para produtos duráveis' : '5 anos, contados a partir do conhecimento do dano'}`;

  function complaintType(data: Partial<ComplaintData>): string {
    switch(data.complaintType) {
      case 'produto_defeituoso':
        return 'produto defeituoso';
      case 'servico_insatisfatorio':
        return 'serviço insatisfatório';
      case 'cobranca_indevida':
        return 'cobrança indevida';
      case 'publicidade_enganosa':
        return 'publicidade enganosa';
      case 'cancelamento_dificil':
        return 'dificuldade de cancelamento';
      case 'atraso_entrega':
        return 'atraso na entrega';
      case 'nao_entregue':
        return 'não entrega do produto';
      default:
        return 'problema';
    }
  }

  function formatDate(dateString?: string): string {
    if (!dateString) return '';
    return new Date(dateString).toLocaleDateString('pt-BR');
  }

  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
      <div className="flex justify-between items-start mb-4">
        <h3 className="text-xl font-semibold text-gray-800">Reclamação Formal</h3>
        
        <div className="flex space-x-2">
          <button 
            onClick={handleCopy} 
            className={`flex items-center px-4 py-2 rounded-md text-sm ${copied ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-700'} transition-colors`}
          >
            {copied ? <Check className="h-4 w-4 mr-1" /> : <Clipboard className="h-4 w-4 mr-1" />}
            {copied ? 'Copiado' : 'Copiar texto'}
          </button>
          
          <button onClick={onSave} className="primary-btn text-sm py-2 flex items-center">
            <FileText className="h-4 w-4 mr-1" />
            Salvar reclamação
          </button>
        </div>
      </div>
      
      <div className="rounded-md bg-gray-50 p-4 mb-6">
        <pre className="text-gray-800 whitespace-pre-wrap font-sans text-sm">
          {sampleFormalComplaint}
        </pre>
      </div>
      
      <div>
        <button 
          onClick={() => toggleSection('simplified')}
          className="flex items-center w-full justify-between bg-consumer-light text-consumer-dark p-3 rounded-t-md font-medium"
        >
          <div className="flex items-center">
            <MessageSquare className="h-5 w-5 mr-2" />
            Explicação Simplificada
          </div>
          {showSimplified ? <ChevronUp className="h-5 w-5" /> : <ChevronDown className="h-5 w-5" />}
        </button>
        
        {showSimplified && (
          <div className="border border-consumer-light rounded-b-md p-4 bg-white">
            <div className="flex items-start mb-3">
              <AlertTriangle className="h-5 w-5 text-amber-500 mt-0.5 mr-2 flex-shrink-0" />
              <p className="text-sm text-gray-600">
                Esta é uma interpretação simplificada dos seus direitos de acordo com o Código de Defesa do Consumidor.
              </p>
            </div>
            
            <div className="text-sm text-gray-800 whitespace-pre-line">
              {simplifiedExplanation}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ComplaintOutput;
